# Generated by Django 5.0.7 on 2024-07-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationlist',
            old_name='notification_type',
            new_name='type',
        ),
    ]
