# Generated by Django 5.0.6 on 2024-06-15 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('icon', models.FileField(upload_to='incident_category_icons/')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incident Category',
                'verbose_name_plural': 'Incident Categories',
                'db_table': 'incident_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='incident_images')),
            ],
            options={
                'db_table': 'incident_images',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('coordinate', models.JSONField(default=dict)),
                ('upvote_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NONE', 'None'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('FIXING', 'Fixing'), ('RESOLVED', 'Resolved')], default='NONE', max_length=10)),
                ('is_accepted_by_org', models.BooleanField(default=False)),
                ('is_internal_for_org', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_by', models.CharField(choices=[('USER', 'User'), ('ORG', 'Org')], default='USER', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_incidents', to=settings.AUTH_USER_MODEL)),
                ('incident_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.incidentcategory')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.incidentimage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.incident')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification List',
                'verbose_name_plural': 'Notifications List',
                'db_table': 'notifications_list',
                'ordering': ['created_at'],
            },
        ),
    ]
