# Generated by Django 5.0.6 on 2024-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('FIXING', 'Fixing'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=10),
        ),
    ]
