# Generated by Django 5.0.6 on 2024-06-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incidentcategory_incidentimage_incident_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='incidents',
        ),
    ]
