# Generated by Django 5.0.6 on 2024-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incident_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='incident',
            name='images',
        ),
        migrations.AddField(
            model_name='incident',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='core.incidentimage'),
        ),
    ]
