# Generated by Django 5.0.6 on 2024-06-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_incident_description_remove_incident_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='project_id',
            new_name='project',
        ),
    ]
