# Generated by Django 5.0.6 on 2024-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_organization_id_project_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
    ]
