# Generated by Django 5.0.6 on 2024-06-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(default=None, null=True, upload_to='user_images/'),
        ),
    ]
