# Generated by Django 5.0.6 on 2024-06-25 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='user_images/'),
            preserve_default=False,
        ),
    ]
