# Generated by Django 5.0.6 on 2024-06-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_points_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, upload_to='user_images/'),
        ),
    ]
