name: alertme-api cd

on:
  push:
    branches: [ "Initiate-code-for-backend-and-run-it-through-docker" ]
    
on:
  workflow_run:
    workflows: ["alertme-api ci"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull langaraspiders/alertme-api:latest

    - name: just say hi
      run: echo "Hi"
