name: alertme-api cd
    


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Pull Docker image
      run: docker pull langaraspiders/alertme-api:latest

    - name: Run Docker container and execute commands
      run: |
        docker run -d --name alertme-api-container -p 8000:8000 langaraspiders/alertme-api:latest sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    - name: Show message on successful deployment
      if: success()
      run: echo "Success"
     
