name: alertme-api cd
    
on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.ref }}
      
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD    

    - name: Create .env file
      run: |
        echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > .env

    - name: Stop and remove existing container
      run: |
        docker stop alertme-api-container || true
        docker rm alertme-api-container || true

    - name: Build compose file
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USER}}
      run: docker compose build app

    - name: Start the container
      run: docker compose up -d app

    - name: Wait for a few seconds to let the container start
      run: sleep 10

    - name: Print container logs for debugging
      run: docker logs alertme-api-container

    - name: Cleanup .env file
      run: rm .env
      
    - name: Show message on successful deployment
      if: success()
      run: echo "Success"
