name: alertme-api cd
    
on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.ref }}
      
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD    

    - name: Create .env file
      run: |
        echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > .env

    - name: Stop and remove existing containers and prune unused data
      run: |
        docker compose down
        docker system prune -a -f

    - name: Build compose file
      run: docker compose build

    - name: Start the containers
      run: docker compose up -d

    - name: Wait for a few seconds to let the container start
      run: sleep 10

    - name: Print container logs for debugging
      run: docker logs alertme-api-container
      
    - name: Show message on successful deployment
      if: success()
      run: echo "Success"
