name: alertme-api cd
    


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull langaraspiders/alertme-api:latest

    - name: just say hi
      run: echo "Hi"
